# Generated by Django 3.2.5 on 2021-07-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquery',
            name='company_name',
            field=models.CharField(choices=[('ALE', 'Allegro'), ('CDR', 'Cdproject'), ('PKN', 'Pknorlen')], max_length=20),
        ),
    ]
