# Generated by Django 3.2.5 on 2021-07-26 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_stockquery_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquery',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
