# Generated by Django 3.2.5 on 2021-07-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_stockquery_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockQuery',
        ),
    ]
