# Generated by Django 3.2.5 on 2021-07-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_stock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='STOCK',
        ),
    ]
