# Generated by Django 3.2.5 on 2021-07-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_alter_stock_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(db_column='NAME', unique=True)),
            ],
            options={
                'db_table': 'COMPANIES',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False},
        ),
    ]
