# Generated by Django 3.2.5 on 2021-07-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0008_auto_20210726_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquery',
            name='company_name',
            field=models.CharField(choices=[('1', 'Allegro'), ('3', 'Cdproject'), ('2', 'Pknorlen')], max_length=20),
        ),
    ]
