# Generated by Django 3.2.5 on 2021-07-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_alter_stockquery_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquery',
            name='company_name',
            field=models.IntegerField(choices=[('1', 'Allegro'), ('3', 'Cdproject'), ('2', 'Pknorlen')]),
        ),
    ]
